name: eco
description: "Eco application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sliding_up_panel: ^2.0.0+1
  dio: ^5.4.3+1
  freezed_annotation:
  json_annotation:
  logger: ^2.3.0
  geolocator: ^12.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  path_provider: ^2.1.3
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  go_router: ^10.1.2
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.0
  flutter_map_marker_cluster: ^1.3.6
  xml: ^6.5.0
  flutter_map_tile_caching: ^9.0.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  json_serializable: ^6.0.0
  freezed:
  riverpod_generator: ^2.4.0


flutter_native_splash:
  image: assets/images/splash.png
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/tracks/
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: VK Sans Display
      fonts:
        - asset: assets/fonts/vk_sans_display_medium.ttf
          weight: 500
        - asset: assets/fonts/vk_sans_display_semibold.ttf
          weight: 600
