// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBev1c8p5C2vT91jT03_0bC47ip57cVbUk',
    appId: '1:323241183056:web:1b12b669540a2779e84e55',
    messagingSenderId: '323241183056',
    projectId: 'eco-hack-22325',
    authDomain: 'eco-hack-22325.firebaseapp.com',
    storageBucket: 'eco-hack-22325.appspot.com',
    measurementId: 'G-CR5FZZKMXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFHZUDScjQcCfPNiBKK5siptdn3ug4QdA',
    appId: '1:323241183056:android:6c3b258eb8cf56b5e84e55',
    messagingSenderId: '323241183056',
    projectId: 'eco-hack-22325',
    storageBucket: 'eco-hack-22325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZfdMJUV1bvJWoSdh1gl9dF5rtJw4bMs',
    appId: '1:323241183056:ios:9e652c91d66b6dc7e84e55',
    messagingSenderId: '323241183056',
    projectId: 'eco-hack-22325',
    storageBucket: 'eco-hack-22325.appspot.com',
    iosBundleId: 'com.example.eco',
  );

}